### PR TITLE
Add `rename` to `registry.json`

### PR DESCRIPTION
**Pull request by Nicklaus-s**

### CODE REVIEW

**Comment by StephenDaDev** [comment]
Also not sure what the icon is

**Comment by Nicklaus-s** [comment]
I've added a permission group check, see line [16](https://github.com/Nicklaus-s/modmail-plugins/blob/aad380de2ebabbae61026b280a9879bac7d550dd/rename/rename.py#L16) & made sure to include a fallback exception, see line [40](https://github.com/Nicklaus-s/modmail-plugins/blob/aad380de2ebabbae61026b280a9879bac7d550dd/rename/rename.py#L40-#L42). I'm not exactly sure if this is what you were asking for, but I believe I've fixed everything.

I've also changed the attached icon.

**Comment by Nicklaus-s** [comment]
chat is it true this from april

**Review by StephenDaDev — APPROVED** [review]

**Comment by StephenDaDev** [comment]
@Taaku18 Recommending for addition in next update

**Comment by StephenDaDev** [comment]
_clicked the wrong button_

**Review by Taaku18 — APPROVED** [review]
Thanks for the addition, will be added to the registry in the next update.

**Pull request merged**
